### ISSUE TITLE
Cant send files

### ISSUE THREAD

**Issue by pingableuser** [Aliucord/Aliucord#185]
### Discord Account

the most sane person here#9049

### What happens when the bug or crash occurs?

What happens is when i press the plus symbol at the bottom left corner to send things, it freezes up then crashes

### What is the expected behaviour?

I want it to actually let me send images and videos instead of freezing up and crashing

### How do you recreate this bug or crash?

All I did it was by pressing the plus symbol

### Crash-log

```
java.lang.RuntimeException: You fool...
	at com.aliucord.settings.Crashes.onViewBound$lambda-11$lambda-10(Crashes.kt:126)
	at com.aliucord.settings.Crashes.$r8$lambda$sjB6qAM5UmxIsY0xBVfW31D8UWE(Unknown Source:0)
	at com.aliucord.settings.Crashes$$ExternalSyntheticLambda4.onClick(Unknown Source:0)
	at android.view.View.performClick(View.java:6291)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
	at android.view.View$PerformClick.run(View.java:24931)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
 
```

### Request Agreement

- [ ] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Vendicated** [comment]
That's not the right stacktrace also not related to Aliucord itself, likely one of your plugins. Use the support channel
