### ISSUE TITLE
Crash on samsung phone

### ISSUE THREAD

**Issue by akiyuee** [Aliucord/Aliucord#210]
### What happens when the bug or crash occurs?

It just randomly crashes when the virtual keyboard closed.

### What is the expected behaviour?

It shouldnt crash

### How do you recreate this bug or crash?

It crashes randomly

### Crash-log

```
java.lang.IllegalStateException: 
Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView() 	
        at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:2) 	
        at com.discord.utilities.viewbinding.FragmentViewBindingDelegate.getValue(FragmentViewBindingDelegate.kt:3)
 	at com.discord.widgets.channels.list.WidgetChannelsList.getBinding(Unknown Source:7)
 	at com.discord.widgets.channels.list.WidgetChannelsList.access$getBinding$p(WidgetChannelsList.kt:1)
 	at com.aliucord.coreplugins.Badges.addGuildBadge(Badges.kt:136)
 	at com.aliucord.coreplugins.Badges.access$addGuildBadge(Badges.kt:29)
 	at com.aliucord.coreplugins.Badges$load$4$1$1.run(Badges.kt:107)
 	at android.os.Handler.handleCallback(Handler.java:938)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:246)
 	at android.app.ActivityThread.main(ActivityThread.java:8653)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by EndermanHackerVN** [comment]
I have an A50s

**Comment by Den4enko** [comment]
This is not a problem with Samsung devices. I have a Samsung Galaxy A52(OneUI 4.1), and everything works fine
