### ISSUE TITLE
Injection failure on Android 8.1

### ISSUE THREAD

**Issue by RhythmLunatic** [Aliucord/Aliucord#241]
PineXposed
```
java.lang.NoSuchMethodError: No static method disableProfileSaver()Z in class Lde/robv/android/xposed/XposedBridge; or its super classes (declaration of 'de.robv.android.xposed.XposedBridge' appears in /data/app/com.aliucord-oYrzRHphOQ6En630_xCD8g==/base.apk!classes5.dex)
	at com.aliucord.injector.InjectorKt.init(Injector.kt:59)
	at com.aliucord.injector.InjectorKt.access$init(Injector.kt:1)
	at com.aliucord.injector.InjectorKt$init$1.beforeHookedMethod(Injector.kt:43)
	at de.robv.android.xposed.XposedBridge$Handler.beforeCall(XposedBridge.java:278)
	at top.canyie.pine.Pine.handleCall(Pine.java:498)
	at top.canyie.pine.entry.Arm64Entry.handleBridge(Arm64Entry.java:159)
	at top.canyie.pine.entry.Arm64Entry.voidBridge(Arm64Entry.java:24)
	at android.app.Activity.performCreate(Activity.java:7041)
	at android.app.Activity.performCreate(Activity.java:7032)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6753)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by Juby210** [comment]
This is not issue on our side. We don't use or support pine anymore. This method comes from our own hook api - https://github.com/Aliucord/hook/blob/main/core/src/main/java/de/robv/android/xposed/XposedBridge.java#L48-L60
