### ISSUE TITLE
Aliucord crashes when I try to verify captcha.

### ISSUE THREAD

**Issue by ghost** [Aliucord/Aliucord#262]
### What happens when the bug or crash occurs?

The crash always happens when I try to login then verify by hcaptcha. Instead it just says check setting for crash logs, but I can't access setting since I can't login.

### What is the expected behaviour?

I expected aliucord to open the captcha page and verify and get me into discord. But instead of that it just says "unrecoverable crash occured, check crash logs in settings"

### How do you recreate this bug or crash?

1.Try to login
2.Click verify button on hcaptcha
3.Crash

### Crash-log
```
android.view.InflateException: Binary XML file line #9 in com.discord:layout/hcaptcha_fragment: Binary XML file line #9 in com.discord:layout/hcaptcha_fragment: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #9 in com.discord:layout/hcaptcha_fragment: Error inflating class <unknown>
Caused by: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
	at android.webkit.WebView.getFactory(WebView.java:2594)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2588)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2656)
	at android.view.View.<init>(View.java:5325)
	at android.view.View.<init>(View.java:5466)
	at android.view.ViewGroup.<init>(ViewGroup.java:702)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:421)
	at android.webkit.WebView.<init>(WebView.java:363)
	at android.webkit.WebView.<init>(WebView.java:345)
	at android.webkit.WebView.<init>(WebView.java:332)
	at android.view.LayoutInflater.tryCreateViewDirect(LayoutInflater.java:1486)
	at android.view.LayoutInflater.createView(LayoutInflater.java:814)
	at android.view.LayoutInflater.createView(LayoutInflater.java:780)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:942)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:962)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1135)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at b.j.a.c.onCreateView(Unknown Source:3)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
	at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:1)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:15)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:20)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:34)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7880)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:355)
	... 40 more
Caused by: pv: errorCode=2
	at lo.e(chromium-SystemWebView.apk-stable-1659916960:889)
	at lo.g(chromium-SystemWebView.apk-stable-1659916960:717)
	at org.chromium.android_webview.AwBrowserProcess.g(chromium-SystemWebView.apk-stable-1659916960:701)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(chromium-SystemWebView.apk-stable-1659916960:446)
	at com.android.webview.chromium.WebViewChromiumFactoryProviderForS.<init>(chromium-SystemWebView.apk-stable-1659916960:13)
	at com.android.webview.chromium.WebViewChromiumFactoryProviderForS.create(chromium-SystemWebView.apk-stable-1659916960:9)
	... 42 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libwebviewchromium.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1656)
	at lo.e(chromium-SystemWebView.apk-stable-1659916960:837)
	... 47 more

```
### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by MeFinity** [comment]
You can check the crashlog via your File Manager,its in Aliucord/crashlogs

**Comment by xeb10** [comment]
Ok, I added crash logs.

**Comment by DiamondMiner88** [comment]
You don't have any native WebView installed, are you using a custom ROM?

**Comment by xeb10** [comment]
Yup. I changed the WebView to default after reading the crash logs and it works.
