### ISSUE TITLE
Crash every open a link

### ISSUE THREAD

**Issue by AdityaMH** [Aliucord/Aliucord#306]
### What happens when the bug or crash occurs?

aliucord always crashed every open a link

### What is the expected behaviour?

just open a link then crash

### How do you recreate this bug or crash?

just open link then crash

### Crash-log

```
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://www.youtube.com/... cmp=id.dana/.home.HomeTabActivity (has extras) } from ProcessRecord{67855ce 8210:com.aliucord/u0a624} (pid=8210, uid=10624) not exported from uid 10563
	at android.os.Parcel.createException(Parcel.java:2074)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.os.Parcel.readException(Parcel.java:1990)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3973)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5277)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivity(Activity.java:5602)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:415)
	at androidx.core.content.ContextCompat$Api16Impl.startActivity(ContextCompat.java:1)
	at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:1)
	at androidx.browser.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:2)
	at com.discord.utilities.uri.UriHandler.openUrl(UriHandler.kt:22)
	at com.discord.utilities.uri.UriHandler.handle(UriHandler.kt:3)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedBridge.invokeMethod(XposedBridge.java:243)
	at de.robv.android.xposed.XposedBridge.-$$Nest$sminvokeMethod(Unknown Source:0)
	at de.robv.android.xposed.XposedBridge$HookInfo.callback(XposedBridge.java:369)
	at LSPHooker_.handle(Unknown Source:31)
	at com.discord.utilities.uri.UriHandler.handle$default(UriHandler.kt:1)
	at b.a.a.g.a.h(WidgetMaskedLinksDialog.kt:1)
	at b.a.a.g.a$a.onClick(java-style lambda group:11)
	at android.view.View.performClick(View.java:7307)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
	at android.view.View.performClickInternal(View.java:7284)
	at android.view.View.access$3600(View.java:821)
	at android.view.View$PerformClick.run(View.java:28053)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:226)
	at android.app.ActivityThread.main(ActivityThread.java:7592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1104)
	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:791)
	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:590)
	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1401)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:521)


```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
1. What ROM are you on
2. what's your default browser

**Comment by AdityaMH** [comment]
MIUI 12, Chrome

**Comment by C10udburst** [comment]
Uninstalling "DANA Indonesian Digital Wallet" should fix this
