### ISSUE TITLE
Aliucord crashing after fresh install

### ISSUE THREAD

**Issue by KaKi87** [Aliucord/Aliucord#389]
### Discord Account

KaKi87#2368

### What happens when the bug or crash occurs?

The "Unfortunately, Aliucord has stopped" error is thrown a split second after clicking Aliucord on the launcher.

Device is a Samsung Galaxy Tab 8.4 on Android 6, non-upgradable.

### What is the expected behaviour?

Aliucord doesn't crash, like Discord on same version (`126.21`) doesn't.

### How do you recreate this bug or crash?

1. Click Aliucord from launcher
2. Observe crash

### Crash-log

```
10-16 09:07:05.496 31057 31057 E Zygote  : v2
10-16 09:07:05.496 31057 31057 W SELinux : Function: selinux_compare_spd_ram, index[1], priority [2], priority version is VE=SEPF_SECMOBILE_6.0.1_0030
10-16 09:07:05.501 31057 31057 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.aliucord 
10-16 09:07:05.551 31057 31057 D TimaKeyStoreProvider: TimaSignature is unavailable
10-16 09:07:05.551 31057 31057 D ActivityThread: Added TimaKeyStore provider
10-16 09:07:06.201 31057 31057 W art     : Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --compiler-filter=speed --instruction-set-variant=cortex-a15 --instruction-set-features=default --dex-file=/data/app/com.aliucord-1/base.apk --oat-file=/data/dalvik-cache/arm/data@app@com.aliucord-1@base.apk@classes.dex) because non-0 exit status
10-16 09:07:06.211 31057 31057 W art     : Failed to open dex file '/data/app/com.aliucord-1/base.apk' from memory: Unrecognized version number in /data/app/com.aliucord-1/base.apk: 0 3 7 
10-16 09:07:06.216 31057 31057 D AndroidRuntime: Shutting down VM
10-16 09:07:06.226 31057 31057 E AndroidRuntime: FATAL EXCEPTION: main
10-16 09:07:06.226 31057 31057 E AndroidRuntime: Process: com.aliucord, PID: 31057
10-16 09:07:06.226 31057 31057 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.discord.app.App: java.lang.ClassNotFoundException: Didn't find class "com.discord.app.App" on path: DexPathList[[zip file "/data/app/com.aliucord-1/base.apk"],nativeLibraryDirectories=[/data/app/com.aliucord-1/lib/arm, /data/app/com.aliucord-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:680)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6401)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:229)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7331)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.discord.app.App" on path: DexPathList[[zip file "/data/app/com.aliucord-1/base.apk"],nativeLibraryDirectories=[/data/app/com.aliucord-1/lib/arm, /data/app/com.aliucord-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1005)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:670)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	... 9 more
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.aliucord-1/base.apk
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:80)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:59)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:279)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:86)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:47)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:438)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at android.app.LoadedApk.makeApplication(LoadedApk.java:663)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		... 9 more
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.discord.app.App
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 		... 12 more
10-16 09:07:06.226 31057 31057 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
10-16 09:07:08.706 31057 31057 I Process : Sending signal. PID: 31057 SIG: 9
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
Please clear installer cache and try reinstalling
 If it does not work then please go to the actual support channel in our support server

**Comment by KaKi87** [comment]
> go to the actual support channel in our support server

[Done](https://discord.com/channels/811255666990907402/811261298997460992/1163384098555969536), thanks
