### ISSUE TITLE
I can't join the Aliucord server

### ISSUE THREAD

**Issue by MarkovType** [Aliucord/Aliucord#398]
### Discord Account

octaviaprinciple

### What happens when the bug or crash occurs?

Hello,
I KNOW ITS NOT the appropriate way to contact you.
But I just installed Aliucord on my new phone and I can't join the Aliucord Discord server. It opens the invite window, I click on accept, the window closes but nothing more happens.
For precision, I have never joined this server before, nor with this account or another, I have never been banned from Discord either. I can join other servers just fine.
I want to retrieve the PluginDownloader package but it is unavailable on the Internet...

I just read that it may be because this account is too young... okay, but I deleted the old one ? I've been trying for 2 weeks now... 

I've used Aliucord before, so just kinda sad that the DownladPlugins isn't available for manual installation...

Thanks for your consideration.

### What is the expected behaviour?

Expecting to be able to join the Aliucord discord server.

### How do you recreate this bug or crash?

1. Click the invite link
2. Press Accept
3. The window closes, Nothing happens

### Crash-log

```
java.lang.RuntimeException: You fool...
	at com.aliucord.settings.Crashes.onViewBound$lambda-5$lambda-4(Crashes.kt:74)
	at com.aliucord.settings.Crashes.$r8$lambda$b72c8wLIqV9HjTF9zltgj8vAcp4(Unknown Source:0)
	at com.aliucord.settings.Crashes$$ExternalSyntheticLambda3.onClick(Unknown Source:0)
	at android.view.View.performClick(View.java:7892)
	at android.widget.TextView.performClick(TextView.java:16219)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30880)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
your account is too new
unbanned
