### ISSUE TITLE
Randomly timed me out for a day

### ISSUE THREAD

**Issue by silvanathecat** [Aliucord/Aliucord#404]
### Discord Account

@silvanathecat

### What happens when the bug or crash occurs?

Got a time out in a server THAT I MODERATE. Nothing in the audit log. Restarted the client and it fixed it.

### What is the expected behaviour?

Not... this...

### How do you recreate this bug or crash?

No clue, haven't screwed around.

### Crash-log

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at j0.j.b.b$b.run(LooperScheduler.java:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 96 byte allocation with 4925568 free bytes and 4810KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at android.text.BoringLayout.make(BoringLayout.java:60)
	at android.widget.TextView.makeSingleLayout(TextView.java:9520)
	at android.widget.TextView.makeNewLayout(TextView.java:9375)
	at android.widget.TextView.onMeasure(TextView.java:9766)
	at androidx.appcompat.widget.AppCompatTextView.onMeasure(AppCompatTextView.java:2)
	at androidx.appcompat.view.menu.ActionMenuItemView.onMeasure(ActionMenuItemView.java:6)
	at android.view.View.measure(View.java:26496)
	at androidx.appcompat.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:36)
	at androidx.appcompat.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:6)
	at androidx.appcompat.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:3)
	at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:1)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:6)
	at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:4)
	at androidx.appcompat.view.menu.MenuBuilder.addInternal(MenuBuilder.java:6)
	at androidx.appcompat.view.menu.MenuBuilder.add(MenuBuilder.java:3)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:2)
	at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:17)
	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:5)
	at androidx.appcompat.widget.Toolbar.inflateMenu(Toolbar.java:1)
	at com.discord.app.AppFragment.setActionBarOptionsMenu(AppFragment.kt:4)
	at com.discord.widgets.friends.WidgetFriendsList.configureToolbar(WidgetFriendsList.kt:6)
	at com.discord.widgets.friends.WidgetFriendsList.updateView(WidgetFriendsList.kt:4)
	at com.discord.widgets.friends.WidgetFriendsList.configureUI(WidgetFriendsList.kt:3)
	at com.discord.widgets.friends.WidgetFriendsList.access$configureUI(WidgetFriendsList.kt:1)
	at com.discord.widgets.friends.WidgetFriendsList$onViewBoundOrOnResume$1.invoke(WidgetFriendsList.kt:2)
	at com.discord.widgets.friends.WidgetFriendsList$onViewBoundOrOnResume$1.invoke(WidgetFriendsList.kt:1)
	at com.discord.utilities.rx.ObservableExtensionsKt$sam$rx_functions_Action1$0.call(Unknown Source:2)
	at j0.l.e.b.onNext(ActionSubscriber.java:1)
	at j0.n.b.onNext(SafeSubscriber.java:2)
	at j0.n.e.onNext(Subscribers.java:1)
	at j0.l.a.l$a.onNext(OnSubscribeFilter.java:2)
	at j0.n.c.onNext(SerializedObserver.java:14)
	at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:1)
	at j0.l.a.d2.onNext(OperatorTakeUntil.java:1)
	at j0.l.a.e.a(NotificationLite.java:7)
	at j0.q.c$b.a(SubjectSubscriptionManager.java:12)
	at rx.subjects.BehaviorSubject.onNext(BehaviorSubject.java:9)
	at b.a.d.d0.updateViewState(AppViewModel.kt:2)
	at com.discord.widgets.friends.FriendsListViewModel.generateLoadedItems(FriendsListViewModel.kt:7)
	at com.discord.widgets.friends.FriendsListViewModel.handleComputedItems(FriendsListViewModel.kt:2)
	at com.discord.widgets.friends.FriendsListViewModel.access$handleComputedItems(FriendsListViewModel.kt:1)
	at com.discord.widgets.friends.FriendsListViewModel$handleStoreState$2.invoke(FriendsListViewModel.kt:4)
	at com.discord.widgets.friends.FriendsListViewModel$handleStoreState$2.invoke(FriendsListViewModel.kt:1)
	at com.discord.widgets.friends.FriendsListViewModel$asyncComputeAndHandleOnUiThread$2.invoke(FriendsListViewModel.kt:2)
	at com.discord.widgets.friends.FriendsListViewModel$asyncComputeAndHandleOnUiThread$2.invoke(FriendsListViewModel.kt:1)
	at com.discord.utilities.rx.ObservableExtensionsKt$sam$rx_functions_Action1$0.call(Unknown Source:2)
	at j0.l.e.b.onNext(ActionSubscriber.java:1)
	at j0.n.b.onNext(SafeSubscriber.java:2)
	at j0.n.e.onNext(Subscribers.java:1)
	at j0.n.c.onNext(SerializedObserver.java:14)
	at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:1)
	at j0.l.a.d2.onNext(OperatorTakeUntil.java:1)
	at j0.l.a.z0$a.call(OperatorObserveOn.java:8)
	at j0.j.b.b$b.run(LooperScheduler.java:1)
	... 8 more
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
most coherent github issue
anyways assuming that stacktrace is actually yours then your device ran out of memory
not an aliucord issue
