### ISSUE TITLE
Audit Log infinitely loads in some servers

### ISSUE THREAD

**Issue by aaronlink127** [Aliucord/Aliucord#432]
### What happens when the bug or crash occurs?

When opening the Audit Log, it seems to infinitely load and logs an error in the debug log. This seems to be because of newer action types, like "Uploaded a Soundboard sound".

### What is the expected behaviour?

Load the Audit Log list properly

### How do you recreate this bug or crash?

1. Navigate to a server
2. Open the Audit Log

### Crash-log

```
StoreAuditLog
java.io.IOException: Unable to parse model.
  at com.discord.models.domain.Model$TypeAdapterFactory$1.read(Model.java, StoreAuditLog:5)
  at i0.e0.a.c.convert(GsonResponseBodyConverter.java:8)
  at i0.p.g(OkHttpCall.java:22)
  at i0.p.execute(OkHttpCall.java:8)
  at i0.d0.a.c.call(CallExecuteOnSubscribe.java:6)
  at i0.d0.a.a.call(BodyOnSubscribe.java:2)
  at rx.Observable.i0(Observable.java:5)
  at j0.l.a.x1$a.call(OperatorSubscribeOn.java:4)
  at j0.l.c.a$b$a.call(CachedThreadScheduler.java:4)
  at j0.l.c.j.run(ScheduledAction.java:2)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
  at java.util.concurrent.FutureTask.run(FutureTask.java:264)
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by KaKi87** [comment]
Hello,
@Juby210 Any news on this ?
Thanks
