### ISSUE TITLE
'Authorized Apps' crashes Aliucord when clicked

### ISSUE THREAD

**Issue by notjak0** [Aliucord/Aliucord#435]
### Discord Account

notjak.

### What happens when the bug or crash occurs?

Alucord crashes whenever the 'Authorized Apps' menu is opened with the message: `An unrecoverable crash occured. Check the crashes menu in the settings for more info.`

### What is the expected behaviour?

Aliucord should show my discord app integrations, but it crashes instead.

### How do you recreate this bug or crash?

1. Click on the profile menu
2. Click on 'Authorized Apps'
3. Aliucord should crash

### Crash-log

```
com.discord.views.OAuthPermissionViews$InvalidScopeException: invalid scope: applications.commands.permissions.update
	at com.discord.views.OAuthPermissionViews.a(OAuthPermissionViews.kt:28)
	at com.discord.views.OAuthPermissionViews$a.bind(OAuthPermissionViews.kt:5)
	at com.discord.utilities.views.SimpleRecyclerAdapter.onBindViewHolder(SimpleRecyclerAdapter.kt:2)
	at com.discord.utilities.views.SimpleRecyclerAdapter.onBindViewHolder(SimpleRecyclerAdapter.kt:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:7)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:55)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:3)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:65)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:26710)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1556)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:846)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:725)
	at android.view.View.measure(View.java:26710)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:198)
	at androidx.cardview.widget.CardView.onMeasure(CardView.java:11)
	at com.google.android.material.card.MaterialCardView.onMeasure(MaterialCardView.java:1)
	at android.view.View.measure(View.java:26710)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:14)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:11)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:65)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:26710)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1556)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:846)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:725)
	at android.view.View.measure(View.java:26710)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:5)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:198)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:1)
	at android.view.View.measure(View.java:26710)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:1)
	at b.i.a.g.a.b.onMeasureChild(HeaderScrollingViewBehavior.java:15)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:34)
	at android.view.View.measure(View.java:26710)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:198)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:26710)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1556)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:846)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:725)
	at android.view.View.measure(View.java:26710)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:198)
	at android.view.View.measure(View.java:26710)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1556)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:846)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:725)
	at android.view.View.measure(View.java:26710)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:198)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:835)
	at android.view.View.measure(View.java:26710)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4241)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2903)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3198)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2610)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9619)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1499)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1114)
	at android.view.Choreographer.doFrame(Choreographer.java:1031)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1467)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by adamperkowski** [comment]
doesnt crash for me

**Comment by void6670** [comment]
easy fix, just go to discord.com/app remove all the authorized apps you don't want and done, should fix it

**Comment by yutaplug** [comment]
for anyone having this issue, please install this plugin:
https://github.com/MCausc78/RNSucks/raw/builds/AuthorizedAppsCrashFix.zip
download it by clicking it, then move the .zip without extracting to the `Aliucord/plugins` folder inside your internal storage.

**Comment by jeantheamazing** [comment]
On September 7, 2025 6:50:43 AM GMT+02:00, yeahsure9 ***@***.***> wrote:
>yeahsure9 left a comment (Aliucord/Aliucord#435)
>
>for anyone having this issue, please install this plugin:
>https://github.com/MCausc78/RNSucks/raw/builds/AuthorizedAppsCrashFix.zip
>download it by clicking it, then move the .zip without extracting to the `Aliucord/plugins` folder inside your internal storage.
>

ok, thanks a lot
