### ISSUE TITLE
Aliucord stopped working after a ROM update (YAAP)

### ISSUE THREAD

**Issue by CognitiveMango** [Aliucord/Aliucord#454]
### Discord Account

cognitivemango

### What happens when the bug or crash occurs?

I use a custom ROM called YAAP. Device is OnePlus 7T Pro running Android 14 QPR2.

Aliucord does not load after the latest ROM update, instead I get stock Discord. Rolling back to the previous ROM build fixes it. The ROM dev thinks upstream ART commits from AOSP 14 might be responsible. I noticed there were similar issues open regarding GrapheneOS, but YAAP doesn't do breaking changes like Graphene.

I'm attaching the [repo](https://github.com/yaap/art/commits/fourteen/) for the ART commits, please let me know if any of the commits from June 4 could break Aliucord. I am attaching a partial logcat of what seem like the relevant lines to me, but I have full logs and root access as well if necessary for further debugging. Other Discord mods like Vendetta/Bunny, and apparently even xposed/lsposed modules are broken with the new ROM update for what it's worth, not that I use them myself.

ART Repo: https://github.com/yaap/art/commits/fourteen/

I read similar Github issues and decided to try the [latest manager version ](https://github.com/Aliucord/Manager/actions/runs/9150645972)available at the time of writing to see if it would fix the issue. I was able to install Aliucord with the manager and granted all file perms, but it did not fix the issue.

### What is the expected behaviour?

I expect Aliucord to load instead of stock Discord. I expect to be able to install and use plugins.

### How do you recreate this bug or crash?

1.  Install [this build ](https://github.com/yaap/ota-info/commit/54e3f5496f9366184681d991b8d84c0b30ac2419)of YAAP.
2. Aliucord will stop working, only stock Discord will work.

### Crash-log

```
06-08 13:39:11.175 W/PackageManager( 1470): No change is needed for package: com.aliucord. Skipping suspending/un-suspending.
06-08 13:39:11.204 W/PackageManager( 1470): No change is needed for package: com.aliucord.installer. Skipping suspending/un-suspending.
06-08 13:39:22.798 I/ActivityTaskManager( 1470): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.aliucord/com.discord.app.AppActivity$Main bnds=[0,387][288,863]} with LAUNCH_SINGLE_TASK from uid 10146 (BAL_ALLOW_ALLOWLISTED_COMPONENT) result code=0
06-08 13:39:22.803 V/WindowManagerShell( 4571): Transition requested (#20): android.os.BinderProxy@97ec751 TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=1304 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.aliucord/com.discord.app.AppActivity$Main } baseActivity=ComponentInfo{com.aliucord/com.discord.app.AppActivity$Main} topActivity=ComponentInfo{com.aliucord/com.discord.app.AppActivity$Main} origActivity=null realActivity=ComponentInfo{com.aliucord/com.discord.app.AppActivity$Main} numActivities=1 lastActiveTime=438512 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@55bbbb6} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=null topActivityInfo=ActivityInfo{490b7 com.discord.app.AppActivity$Main} launchCookies=[android.os.BinderProxy@a939024] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 isUserFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@697878d, appThread = android.app.IApplicationThread$Stub$Proxy@ddfdd42, debugName = QuickstepLaunch }, displayChange = null, flags = 0, debugId = 20 }
06-08 13:39:22.830 I/ActivityManager( 1470): Start proc 9301:com.aliucord/u0a302 for next-top-activity {com.aliucord/com.discord.app.AppActivity$Main}
06-08 13:39:22.840 I/com.aliucord( 9301): Using CollectorTypeCC GC.
06-08 13:39:22.843 E/com.aliucord( 9301): Not starting debugger since process cannot load the jdwp agent.
06-08 13:39:22.858 D/CoreBackPreview( 1470): Window{2da0215 u0 Splash Screen com.aliucord}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@fd1931b, mPriority=0, mIsAnimationCallback=false}
06-08 13:39:22.869 V/WindowManager( 1470): Sent Transition (#20) createdAt=06-08 13:39:22.791 via request=TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=1304 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.aliucord/com.discord.app.AppActivity$Main } baseActivity=ComponentInfo{com.aliucord/com.discord.app.AppActivity$Main} topActivity=ComponentInfo{com.aliucord/com.discord.app.AppActivity$Main} origActivity=null realActivity=ComponentInfo{com.aliucord/com.discord.app.AppActivity$Main} numActivities=1 lastActiveTime=438512 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{9954a93 Task{23d3746 #1304 type=standard A=10302:com.aliucord}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=null topActivityInfo=ActivityInfo{1fbbad0 com.discord.app.AppActivity$Main} launchCookies=[android.os.BinderProxy@7fa1ac9] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 isUserFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@a1cd5ce, appThread = android.app.IApplicationThread$Stub$Proxy@2bffcef, debugName = QuickstepLaunch }, displayChange = null, flags = 0, debugId = 20 }
06-08 13:39:22.869 V/WindowManager( 1470):         {WCT{RemoteToken{9954a93 Task{23d3746 #1304 type=standard A=10302:com.aliucord}}} m=OPEN f=NONE leash=Surface(name=Task=1304)/@0xa295ecd sb=Rect(0, 0 - 1440, 3120) eb=Rect(0, 0 - 1440, 3120) d=0},
06-08 13:39:22.974 D/nativeloader( 9301): Configuring clns-4 for other apk /data/app/~~pPNbmP0NY-_djgdDN0sJLg==/com.aliucord-Jv1gASQ_mR_Oq2fLe3w-eA==/base.apk. target_sdk_version=29, uses_libraries=, library_path=/data/app/~~pPNbmP0NY-_djgdDN0sJLg==/com.aliucord-Jv1gASQ_mR_Oq2fLe3w-eA==/lib/arm64:/data/app/~~pPNbmP0NY-_djgdDN0sJLg==/com.aliucord-Jv1gASQ_mR_Oq2fLe3w-eA==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.aliucord
06-08 13:39:23.025 D/nativeloader( 9301): Load /data/app/~~pPNbmP0NY-_djgdDN0sJLg==/com.aliucord-Jv1gASQ_mR_Oq2fLe3w-eA==/lib/arm64/libaliuhook.so using ns clns-4 from class loader (caller=<<private info omitted>>): ok
06-08 13:39:23.032 W/AliuHook( 9301): found symtab /apex/com.android.art/lib64/libart.so
06-08 13:39:23.073 W/System  ( 1470): A resource failed to call release. 
06-08 13:39:23.083 E/LSPlant ( 9301): Hook Fails: _ZN3art3jit12JitCodeCache19GarbageCollectCacheEPNS_6ThreadE
06-08 13:39:23.083 E/LSPlant ( 9301): Failed to init jit code cache
06-08 13:39:23.083 E/AliuHook( 9301): lsplant init failed
06-08 13:39:23.083 E/Injector( 9301): Failed to initialize Aliucord
06-08 13:39:23.083 E/Injector( 9301): java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/~~pPNbmP0NY-_djgdDN0sJLg==/com.aliucord-Jv1gASQ_mR_Oq2fLe3w-eA==/lib/arm64/libaliuhook.so"
06-08 13:39:23.083 E/Injector( 9301): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
06-08 13:39:23.083 E/Injector( 9301): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
06-08 13:39:23.083 E/Injector( 9301): 	at java.lang.System.loadLibrary(System.java:1765)
06-08 13:39:23.083 E/Injector( 9301): 	at de.robv.android.xposed.XposedBridge.<clinit>(XposedBridge.java:29)
06-08 13:39:23.083 E/Injector( 9301): 	at com.aliucord.injector.InjectorKt.init(Injector.kt:41)
06-08 13:39:23.083 E/Injector( 9301): 	at com.discord.app.App$a.<clinit>(App$a.java:18)
06-08 13:39:23.083 E/Injector( 9301): 	at com.discord.app.App.<clinit>(Unknown Source:0)
06-08 13:39:23.083 E/Injector( 9301): 	at java.lang.Class.newInstance(Native Method)
06-08 13:39:23.083 E/Injector( 9301): 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
06-08 13:39:23.083 E/Injector( 9301): 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:1)
06-08 13:39:23.083 E/Injector( 9301): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1346)
06-08 13:39:23.083 E/Injector( 9301): 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
06-08 13:39:23.083 E/Injector( 9301): 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
06-08 13:39:23.083 E/Injector( 9301): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7273)
06-08 13:39:23.083 E/Injector( 9301): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
06-08 13:39:23.083 E/Injector( 9301): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
06-08 13:39:23.083 E/Injector( 9301): 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-08 13:39:23.083 E/Injector( 9301): 	at android.os.Looper.loopOnce(Looper.java:232)
06-08 13:39:23.083 E/Injector( 9301): 	at android.os.Looper.loop(Looper.java:317)
06-08 13:39:23.083 E/Injector( 9301): 	at android.app.ActivityThread.main(ActivityThread.java:8506)
06-08 13:39:23.083 E/Injector( 9301): 	at java.lang.reflect.Method.invoke(Native Method)
06-08 13:39:23.083 E/Injector( 9301): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:554)
06-08 13:39:23.083 E/Injector( 9301): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
06-08 13:39:23.090 D/CompatibilityChangeReporter( 9301): Compat change id reported: 183155436; UID 10302; state: DISABLED
06-08 13:39:23.090 I/FirebaseApp( 9301): Device unlocked: initializing all Firebase APIs for app [DEFAULT]
06-08 13:39:23.095 D/nativeloader( 9301): Load /data/app/~~pPNbmP0NY-_djgdDN0sJLg==/com.aliucord-Jv1gASQ_mR_Oq2fLe3w-eA==/lib/arm64/libcrashlytics.so using ns clns-4 from class loader (caller=<<private info omitted>>): ok
06-08 13:39:23.125 W/com.aliucord( 9301): Unsupported class loader
06-08 13:39:23.304 D/SoLoader( 9301): adding application source: b.f.m.c[root = /data/app/~~pPNbmP0NY-_djgdDN0sJLg==/com.aliucord-Jv1gASQ_mR_Oq2fLe3w-eA==/lib/arm64 flags = 0]
06-08 13:39:23.304 D/SoLoader( 9301): adding backup source from : b.f.m.a[root = /data/user/0/com.aliucord/lib-main flags = 1]
06-08 13:39:23.304 D/SoLoader( 9301): Preparing SO source: b.f.m.c[root = /system/lib64 flags = 2]
06-08 13:39:23.304 D/SoLoader( 9301): Preparing SO source: b.f.m.c[root = /vendor/lib64 flags = 2]
06-08 13:39:23.304 D/SoLoader( 9301): Preparing SO source: b.f.m.c[root = /data/app/~~pPNbmP0NY-_djgdDN0sJLg==/com.aliucord-Jv1gASQ_mR_Oq2fLe3w-eA==/lib/arm64 flags = 0]
06-08 13:39:23.304 D/SoLoader( 9301): Preparing SO source: b.f.m.a[root = /data/user/0/com.aliucord/lib-main flags = 1]
06-08 13:39:23.305 V/fb-UnpackingSoSource( 9301): locked dso store /data/user/0/com.aliucord/lib-main
06-08 13:39:23.306 I/fb-UnpackingSoSource( 9301): dso store is up-to-date: /data/user/0/com.aliucord/lib-main
06-08 13:39:23.306 V/fb-UnpackingSoSource( 9301): releasing dso store lock for /data/user/0/com.aliucord/lib-main
06-08 13:39:23.306 D/SoLoader( 9301): init finish: 4 SO sources prepared
06-08 13:39:23.306 D/SoLoader( 9301): init exiting
06-08 13:39:23.315 D/nativeloader( 9301): Load /data/app/~~pPNbmP0NY-_djgdDN0sJLg==/com.aliucord-Jv1gASQ_mR_Oq2fLe3w-eA==/lib/arm64/libdsti.so using ns clns-4 from class loader (caller=<<private info omitted>>): ok

```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by CognitiveMango** [comment]
Fixed with the Android 14 QPR3 update, I'm guessing either Google or my maintainer dropped the breaking ART commits. Not sure if that's a temporary or permanent decision though.

**Comment by CognitiveMango** [comment]
My maintainer rebased on QPR3, and the breaking upstream ART commits are back again. I don't seem to have the permissions to re-open this issue, so I'd appreciate if someone else could. Relevant commits were added in July in [this repo](https://github.com/yaap/art/commits/fourteen/) according to my maintainer.

**Comment by Juby210** [comment]
Fixed in Installer https://github.com/Aliucord/Aliucord/releases/tag/1.2.0 which includes 0e6c2a266545f4956aba3c37c445de27bd6ccce2
