### ISSUE TITLE
Aliucord features disappearing in A15 Beta 4

### ISSUE THREAD

**Issue by RybazPolski** [Aliucord/Aliucord#466]
### Discord Account

itspolishfish

### What happens when the bug or crash occurs?

After I updated my Android from 15 Beta 3 to Android 15 Beta 4 on Google Pixel 7 device my Aliucord suddenly lost all it's features - I have a plain old Discord without plugins (but ones I installed before are still in app files tho). All Aliucord settings including crash log disappeared as well. I tried clean reinstalling but it didn't work.
![Screenshot_20240721-234207](https://github.com/user-attachments/assets/a63e05a1-23fa-4eab-8ce5-0d9601f77476)

### What is the expected behaviour?

Working Aliucord with it's features would be nice

### How do you recreate this bug or crash?

1. Update your phone to Android 15 Beta 4
2. Open Aliucord 
3. That's it. You will se plain old Discord and nothing more

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by bappitybup** [comment]
same issue here. can confirm it's the Android 15 beta

**Comment by OmegaSunkey** [comment]
anything about A15 beta 4 cant be fixed in Aliucord for now. You'll have to downgrade or wait for someone to fix lspatch.

**Comment by Coll147** [comment]
Same issue here, Android 14 QPR3

**Comment by AGuyNamedJens** [comment]
Same here, stable Android 14 July 2024 security patch on Google Pixel 8 Pro
Should a contributor need any logs, tell me.. I'm not running any betas at all, so i assume unlike A15 beta someone can figure out what's up on A14?

**Comment by AGuyNamedJens** [comment]
To add to this, maybe it'll help the devs here
```--------- beginning of main
08-14 15:18:24.854 21409 21409 E Injector: Failed to initialize Aliucord
08-14 15:18:24.854 21409 21409 E Injector: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/~~voH8F3tjgEvj1OHvzWBlEA==/com.aliucord-dAU7D1MrlTL6QhxkC0_MhQ==/lib/arm64/libaliuhook.so"
08-14 15:18:24.854 21409 21409 E Injector:      at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
08-14 15:18:24.854 21409 21409 E Injector:      at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
08-14 15:18:24.854 21409 21409 E Injector:      at java.lang.System.loadLibrary(System.java:1765)
08-14 15:18:24.854 21409 21409 E Injector:      at de.robv.android.xposed.XposedBridge.<clinit>(XposedBridge.java:29)
08-14 15:18:24.854 21409 21409 E Injector:      at com.aliucord.injector.InjectorKt.init(Injector.kt:41)
08-14 15:18:24.854 21409 21409 E Injector:      at com.discord.app.App$a.<clinit>(App$a.java:18)
08-14 15:18:24.854 21409 21409 E Injector:      at com.discord.app.App.<clinit>(Unknown Source:0)
08-14 15:18:24.854 21409 21409 E Injector:      at java.lang.Class.newInstance(Native Method)
08-14 15:18:24.854 21409 21409 E Injector:      at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
08-14 15:18:24.854 21409 21409 E Injector:      at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:1)
08-14 15:18:24.854 21409 21409 E Injector:      at android.app.Instrumentation.newApplication(Instrumentation.java:1352)
08-14 15:18:24.854 21409 21409 E Injector:      at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
08-14 15:18:24.854 21409 21409 E Injector:      at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
08-14 15:18:24.854 21409 21409 E Injector:      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7359)
08-14 15:18:24.854 21409 21409 E Injector:      at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
08-14 15:18:24.854 21409 21409 E Injector:      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
08-14 15:18:24.854 21409 21409 E Injector:      at android.os.Handler.dispatchMessage(Handler.java:107)
08-14 15:18:24.854 21409 21409 E Injector:      at android.os.Looper.loopOnce(Looper.java:232)
08-14 15:18:24.854 21409 21409 E Injector:      at android.os.Looper.loop(Looper.java:317)
08-14 15:18:24.854 21409 21409 E Injector:      at android.app.ActivityThread.main(ActivityThread.java:8592)
08-14 15:18:24.854 21409 21409 E Injector:      at java.lang.reflect.Method.invoke(Native Method)
08-14 15:18:24.854 21409 21409 E Injector:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
08-14 15:18:24.854 21409 21409 E Injector:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by Juby210** [comment]
Fixed in Installer https://github.com/Aliucord/Aliucord/releases/tag/1.2.0 which includes 0e6c2a266545f4956aba3c37c445de27bd6ccce2
