### ISSUE TITLE
Aliucord crashes on pressing and holding a message

### ISSUE THREAD

**Issue by Farajo001** [Aliucord/Aliucord#483]
### What happens when the bug or crash occurs?

The crash happens whenever you press and hold a message to bring up the contextual menu of the message.

### What is the expected behaviour?

I expect Aliucord to open the contextual menu

### How do you recreate this bug or crash?

1. Chose any message you want
2. Press and hold
3. Boom, it crashes

### Crash-log

android.content.res.Resources$NotFoundException: Can't find ColorStateList from drawable resource ID #0x10800a9
	at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1018)
	at android.content.res.Resources.loadColorStateList(Resources.java:1030)
	at android.content.res.TypedArray.getColor(TypedArray.java:461)
	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2443)
	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2733)
	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2078)
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:14)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:2)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:1)
	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:2)
	at com.google.android.material.bottomsheet.BottomSheetDialog.setContentView(BottomSheetDialog.java:2)
	at androidx.fragment.app.DialogFragment$4.onChanged(DialogFragment.java:10)
	at androidx.fragment.app.DialogFragment$4.onChanged(DialogFragment.java:1)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:9)
	at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:1)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:15)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:20)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:34)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6647)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by OmegaSunkey** [comment]
please show your plugins list

**Comment by Farajo001** [comment]
![Screenshot_20240916-112117](https://github.com/user-attachments/assets/92484956-8810-46a4-b3f6-085e663ad450)
![Screenshot_20240916-112121](https://github.com/user-attachments/assets/42a6d5c4-feb4-4247-bbd8-b2e8a56d1458)

**Comment by Farajo001** [comment]
I've just installed it, it is as bone stock as it can be

**Comment by OmegaSunkey** [comment]
try reinstalling

**Comment by rushiiMachine** [comment]
android version/ROM?

**Comment by Farajo001** [comment]
https://github.com/Aliucord/Aliucord/issues/483#issuecomment-2353105893
I tried that already, no luck

**Comment by Farajo001** [comment]
> android version/ROM?

Android 8.1 Go, stock ROM

**Comment by rushiiMachine** [comment]
Please provide a full unfiltered logcat

**Comment by Farajo001** [comment]
I don't have a rooted phone and I don't have access to my PC currently to run ADB or Android Studio

**Comment by rushiiMachine** [comment]
shizuku+wadb

**Comment by Farajo001** [comment]
I've managed to generate a crash and I've filtered by errors, this is what I've got
`09-17 01:03:27.043 18438 18438 E AndroidRuntime: FATAL EXCEPTION: main
09-17 01:03:27.043 18438 18438 E AndroidRuntime: Process: com.aliucord, PID: 18438
09-17 01:03:27.043 18438 18438 E AndroidRuntime: android.content.res.Resources$NotFoundException: Can't find ColorStateList from drawable resource ID #0x10800a9
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1018)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at android.content.res.Resources.loadColorStateList(Resources.java:1030)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at android.content.res.TypedArray.getColor(TypedArray.java:461)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2443)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2733)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2078)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:14)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:2)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:1)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:2)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at com.google.android.material.bottomsheet.BottomSheetDialog.setContentView(BottomSheetDialog.java:2)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.fragment.app.DialogFragment$4.onChanged(DialogFragment.java:10)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.fragment.app.DialogFragment$4.onChanged(DialogFragment.java:1)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:9)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:1)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:15)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:20)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:34)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:1)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6647)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
09-17 01:03:27.043 18438 18438 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)`

**Comment by rushiiMachine** [comment]
outdated ROM issue, unrelated to aliucord
