### ISSUE TITLE
Aliucord is very broken

### ISSUE THREAD

**Issue by aqilc** [Aliucord/Aliucord#503]
### Discord Account

aqilc

### What happens when the bug or crash occurs?

This bug happens all the time when I open the app, although the video has the bug a bit more exaggerated. Since 2 days ago, I have not been able to go to DMs, and can only visit one or two channels in a server before everything dies/crashes.

https://github.com/user-attachments/assets/9ec51fb3-66fd-43f7-8dbf-b66936dd1cb2

### What is the expected behaviour?

For anything to display properly 😭

### How do you recreate this bug or crash?

Open the app

### Crash-log

It doesn't crash.

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by aqilc** [comment]
Is there any way to fix something like this, or any fix being pushed for it? I desperately need access to the much better usable version of the discord app as the most recent versions are slow, bug prone, battery hogs and a genuine pain to use and mod.

**Comment by kekkodance** [comment]
it's christmas dude

**Comment by aqilc** [comment]
This is what happens every single time I open it today.
Right before this, it also says that a network error occurred when I have Internet working perfectly everywhere else.

![Screenshot_20241224_205105_Kvaesitso.jpg](https://github.com/user-attachments/assets/5a0c08b4-962e-4674-9743-0108b9cf5785)

**Comment by rushiiMachine** [comment]
Alright then, send the crashlog instead. Located under `~/Aliucord/crashlogs`

**Comment by aqilc** [comment]
```
java.lang.IllegalArgumentException: method com.discord.models.user.CoreUser.<init> argument 1 has type com.discord.api.user.User, got java.lang.String
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedBridge.invokeMethod(XposedBridge.java:243)
	at de.robv.android.xposed.XposedBridge.-$$Nest$sminvokeMethod(Unknown Source:0)
	at de.robv.android.xposed.XposedBridge$HookInfo.callback(XposedBridge.java:369)
	at LSPHooker_.constructor(Unknown Source:11)
	at com.discord.api.channel.ChannelUtils.a(ChannelUtils.kt:2)
	at com.discord.utilities.icon.IconUtils.getForChannel(IconUtils.kt:7)
	at com.discord.utilities.icon.IconUtils.getForChannel$default(IconUtils.kt:2)
	at com.discord.utilities.icon.IconUtils.setIcon(IconUtils.kt:18)
	at com.discord.utilities.icon.IconUtils.setIcon$default(IconUtils.kt:7)
	at com.discord.widgets.guilds.list.GuildListViewHolder$PrivateChannelViewHolder.configure(GuildListViewHolder.kt:7)
	at com.discord.widgets.guilds.list.WidgetGuildListAdapter.onBindViewHolder(WidgetGuildListAdapter.kt:8)
	at com.discord.widgets.guilds.list.WidgetGuildListAdapter.onBindViewHolder(WidgetGuildListAdapter.kt:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:7)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:55)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:3)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:65)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.discord.panels.OverlappingPanelsLayout.onLayout(OverlappingPanelsLayout.kt:1)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1102)
	at android.view.View.layout(View.java:25788)
	at android.view.ViewGroup.layout(ViewGroup.java:6874)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:5349)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4589)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3345)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11437)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1690)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1154)
	at android.view.Choreographer.doFrame(Choreographer.java:1080)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

I think this is the most recent one.

**Comment by aqilc** [comment]
> it's christmas dude

I still get so many notifications I can't respond to. Thank you all so much for working to fix these problems today! I cannot thank you guys enough I have been using this app for years and I'm scared the day it could get outdated gets ever so closer. Very glad today isn't it. I switched to the Mobile Browser for Discord for the time being for important responses.

**Comment by rushiiMachine** [comment]
Have you
1. Uninstalled & installed via the installer again
2. Tried removing (or moving away) all the plugins from `~/Aliucord/plugins`

**Comment by aqilc** [comment]
I have tried uninstalling and reinstalling it. I also tried disabling all plugins through the settings when it was available. I will try to rename the plugins folder and reinstalling ASAP!

**Comment by aqilc** [comment]
Oh that actually fixed it. I still go to some channels and they don't refresh/a lot of the attachments don't load but some do work and I can send messages now, so it's a lot better! Thank you.

**Comment by aqilc** [comment]
Is there a way to debug what part of the app is doing this?

**Comment by rushiiMachine** [comment]
If there are no plugins in the plugins folder, then any remaining showing under the plugins page are built-in and cannot be removed

I honestly don't have any idea why that crash occurred other than perhaps you were on an ancient version of Discord

**Comment by aqilc** [comment]
I have had it updated for years, and this started occurring randomly a few days ago :(

**Comment by aqilc** [comment]
Also, I toggled the Built In plugins and it only showed 7. Unless there's somehow more plugins that are hidden even when they're toggled to show, this is still very weird.

**Comment by rushiiMachine** [comment]
What Android version and ROM?

**Comment by aqilc** [comment]
Android 14, Samsung's ROM? I don't know how to find that out exactly.

**Comment by rushiiMachine** [comment]
Did you recently update to A14?

**Comment by aqilc** [comment]
Oh I'm so sorry I didn't get an email for that notif. I have been on the same phone, Samsung S22 Ultra for a while.

**Comment by aqilc** [comment]
Android 14 came to me December 15, 2023, so pretty much about a year ago.
