### ISSUE TITLE
[Installer] error 'null' while loading keystore

### ISSUE THREAD

**Issue by Bluscream** [Aliucord/Aliucord#84]
![Screenshot_2021-08-23-16-56-53-815](https://user-images.githubusercontent.com/3318223/130469883-edff2a13-743e-445a-bb31-02ce41ee7531.jpeg)

**Comment by Bluscream** [comment]
```
Signing apk file
null
   at java.io.DataInputStream.readFully(DataInputStream.java:200)
   at java.io.DataInputStream.readFully(DataInputStream.java:172)
   at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineLoad(BcKeyStoreSpi.java:886)
   at java.security.KeyStore.load(KeyStore.java:1484)
   at com.aliucord.installer.Signer.signApk(Signer.java:78)
   at com.aliucord.installer.MainActivity.lambda$onCreate$9(MainActivity.java:199)
   at com.aliucord.installer.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:4)
   at java.lang.Thread.run(Thread.java:919)
```

**Comment by Bluscream** [comment]
Can someone help with this?

**Comment by Juby210** [comment]
I don't really have any idea with this issue, you might just try to use other app to sign Aliucord from `storage/Aliucord/Aliucord.apk`.

**Comment by Bluscream** [comment]
> I don't really have any idea with this issue, you might just try to use other app to sign Aliucord from `storage/Aliucord/Aliucord.apk`. 

Which apk should i use instead?

**Comment by Vendicated** [comment]
[Mixplorer](https://forum.xda-developers.com/t/app-2-2-mixplorer-v6-x-released-fully-featured-file-manager.1523691/) can sign apks

**Comment by Bluscream** [comment]
It finally randomly decided to work after installing MiX

**Comment by Bluscream** [comment]
https://play.google.com/store/apps/details?id=com.andatsoft.myapk.fwa can also sign apk files now
